'use strict';

module.exports = {
  async up (queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Words', [
      { word: "forest", wordTypeId: 1 },
      { word: "oil", wordTypeId: 1 },
      { word: "garden", wordTypeId: 1 },
      { word: "fountain", wordTypeId: 1 },
      { word: "orange", wordTypeId: 1 },
      { word: "France", wordTypeId: 1 },
      { word: "horse", wordTypeId: 1 },
      { word: "ice", wordTypeId: 1 },
      { word: "oxygen", wordTypeId: 1 },
      { word: "assist", wordTypeId: 2 },
      { word: "attack", wordTypeId: 2 },
      { word: "bake", wordTypeId: 2 },
      { word: "bathe", wordTypeId: 2 },
      { word: "be", wordTypeId: 2 },
      { word: "beat", wordTypeId: 2 },
      { word: "lie", wordTypeId: 2 },
      { word: "lend", wordTypeId: 2 },
      { word: "laugh", wordTypeId: 2 },
      { word: "busy", wordTypeId: 3 },
      { word: "calm", wordTypeId: 3 },
      { word: "careful", wordTypeId: 3 },
      { word: "hilarious", wordTypeId: 3 },
      { word: "homeless", wordTypeId: 3 },
      { word: "poor", wordTypeId: 3 },
      { word: "powerful", wordTypeId: 3 },
      { word: "cute", wordTypeId: 3 },
      { word: "dark", wordTypeId: 3 },
      { word: "badly", wordTypeId: 4 },
      { word: "boastfully", wordTypeId: 4 },
      { word: "enviously", wordTypeId: 4 },
      { word: "foolishly", wordTypeId: 4 },
      { word: "innocently", wordTypeId: 4 },
      { word: "happily", wordTypeId: 4 },
      { word: "kindly", wordTypeId: 4 },
      { word: "gracefully", wordTypeId: 4 },
      { word: "defiantly", wordTypeId: 4 },
      { word: "he", wordTypeId: 5 },
      { word: "she", wordTypeId: 5 },
      { word: "his", wordTypeId: 5 },
      { word: "hers", wordTypeId: 5 },
      { word: "they", wordTypeId: 5 },
      { word: "them", wordTypeId: 5 },
      { word: "theirs", wordTypeId: 5 },
      { word: "yours", wordTypeId: 5 },
      { word: "who", wordTypeId: 5 },
      { word: "what", wordTypeId: 5 },
      { word: "where", wordTypeId: 5 },
      { word: "when", wordTypeId: 5 },
      { word: "into", wordTypeId: 6 },
      { word: "near", wordTypeId: 6 },
      { word: "of", wordTypeId: 6 },
      { word: "off", wordTypeId: 6 },
      { word: "on", wordTypeId: 6 },
      { word: "out", wordTypeId: 6 },
      { word: "over", wordTypeId: 6 },
      { word: "through", wordTypeId: 6 },
      { word: "to", wordTypeId: 6 },
      { word: "toward", wordTypeId: 6 },
      { word: "and", wordTypeId: 7 },
      { word: "that", wordTypeId: 7 },
      { word: "but", wordTypeId: 7 },
      { word: "or", wordTypeId: 7 },
      { word: "as", wordTypeId: 7 },
      { word: "if", wordTypeId: 7 },
      { word: "when", wordTypeId: 7 },
      { word: "than", wordTypeId: 7 },
      { word: "because", wordTypeId: 7 },
      { word: "while", wordTypeId: 7 },
      { word: "all", wordTypeId: 8 },
      { word: "what", wordTypeId: 8 },
      { word: "such", wordTypeId: 8 },
      { word: "rather", wordTypeId: 8 },
      { word: "each", wordTypeId: 8 },
      { word: "every", wordTypeId: 8 },
      { word: "neither", wordTypeId: 8 },
      { word: "many", wordTypeId: 8 },
      { word: "enough", wordTypeId: 8 },
      { word: "several", wordTypeId: 8 },
      { word: "aha", wordTypeId: 9 },
      { word: "hurrah", wordTypeId: 9 },
      { word: "rah", wordTypeId: 9 },
      { word: "whee", wordTypeId: 9 },
      { word: "yippee", wordTypeId: 9 },
      { word: "golly", wordTypeId: 9 },
      { word: "huh", wordTypeId: 9 },
      { word: "yikes", wordTypeId: 9 },
      { word: "zowie", wordTypeId: 9 },
      { word: "mmmm", wordTypeId: 9 },
      ])
  },

  async down (queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Words');
  }
};