'use strict';

module.exports = {
  async up (queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Words', [
      { value: "forest", wordTypeId: 1 },
      { value: "oil", wordTypeId: 1 },
      { value: "garden", wordTypeId: 1 },
      { value: "fountain", wordTypeId: 1 },
      { value: "orange", wordTypeId: 1 },
      { value: "France", wordTypeId: 1 },
      { value: "horse", wordTypeId: 1 },
      { value: "ice", wordTypeId: 1 },
      { value: "oxygen", wordTypeId: 1 },
      { value: "assist", wordTypeId: 2 },
      { value: "attack", wordTypeId: 2 },
      { value: "bake", wordTypeId: 2 },
      { value: "bathe", wordTypeId: 2 },
      { value: "be", wordTypeId: 2 },
      { value: "beat", wordTypeId: 2 },
      { value: "lie", wordTypeId: 2 },
      { value: "lend", wordTypeId: 2 },
      { value: "laugh", wordTypeId: 2 },
      { value: "busy", wordTypeId: 3 },
      { value: "calm", wordTypeId: 3 },
      { value: "careful", wordTypeId: 3 },
      { value: "hilarious", wordTypeId: 3 },
      { value: "homeless", wordTypeId: 3 },
      { value: "poor", wordTypeId: 3 },
      { value: "powerful", wordTypeId: 3 },
      { value: "cute", wordTypeId: 3 },
      { value: "dark", wordTypeId: 3 },
      { value: "badly", wordTypeId: 4 },
      { value: "boastfully", wordTypeId: 4 },
      { value: "enviously", wordTypeId: 4 },
      { value: "foolishly", wordTypeId: 4 },
      { value: "innocently", wordTypeId: 4 },
      { value: "happily", wordTypeId: 4 },
      { value: "kindly", wordTypeId: 4 },
      { value: "gracefully", wordTypeId: 4 },
      { value: "defiantly", wordTypeId: 4 },
      { value: "he", wordTypeId: 5 },
      { value: "she", wordTypeId: 5 },
      { value: "his", wordTypeId: 5 },
      { value: "hers", wordTypeId: 5 },
      { value: "they", wordTypeId: 5 },
      { value: "them", wordTypeId: 5 },
      { value: "theirs", wordTypeId: 5 },
      { value: "yours", wordTypeId: 5 },
      { value: "who", wordTypeId: 5 },
      { value: "what", wordTypeId: 5 },
      { value: "where", wordTypeId: 5 },
      { value: "when", wordTypeId: 5 },
      { value: "into", wordTypeId: 6 },
      { value: "near", wordTypeId: 6 },
      { value: "of", wordTypeId: 6 },
      { value: "off", wordTypeId: 6 },
      { value: "on", wordTypeId: 6 },
      { value: "out", wordTypeId: 6 },
      { value: "over", wordTypeId: 6 },
      { value: "through", wordTypeId: 6 },
      { value: "to", wordTypeId: 6 },
      { value: "toward", wordTypeId: 6 },
      { value: "and", wordTypeId: 7 },
      { value: "that", wordTypeId: 7 },
      { value: "but", wordTypeId: 7 },
      { value: "or", wordTypeId: 7 },
      { value: "as", wordTypeId: 7 },
      { value: "if", wordTypeId: 7 },
      { value: "when", wordTypeId: 7 },
      { value: "than", wordTypeId: 7 },
      { value: "because", wordTypeId: 7 },
      { value: "while", wordTypeId: 7 },
      { value: "all", wordTypeId: 8 },
      { value: "what", wordTypeId: 8 },
      { value: "such", wordTypeId: 8 },
      { value: "rather", wordTypeId: 8 },
      { value: "each", wordTypeId: 8 },
      { value: "every", wordTypeId: 8 },
      { value: "neither", wordTypeId: 8 },
      { value: "many", wordTypeId: 8 },
      { value: "enough", wordTypeId: 8 },
      { value: "several", wordTypeId: 8 },
      { value: "aha", wordTypeId: 9 },
      { value: "hurrah", wordTypeId: 9 },
      { value: "rah", wordTypeId: 9 },
      { value: "whee", wordTypeId: 9 },
      { value: "yippee", wordTypeId: 9 },
      { value: "golly", wordTypeId: 9 },
      { value: "huh", wordTypeId: 9 },
      { value: "yikes", wordTypeId: 9 },
      { value: "zowie", wordTypeId: 9 },
      { value: "mmmm", wordTypeId: 9 },
      ])
  },

  async down (queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Words');
  }
};